// Объявление ссылок на инструкции
static const void (*instruction[256])() = {

    /* 00 */ & Grp1A,              // ADD Eb, Gb
    /* 01 */ & Grp1A,              // ADD Ev, Gb
    /* 02 */ & Grp1A,              // ADD Gb, Eb
    /* 03 */ & Grp1A,              // ADD Gv, Ev
    /* 04 */ & UD,
    /* 05 */ & UD,
    /* 06 */ & UD,
    /* 07 */ & UD,

    /* 08 */ & Grp1A,
    /* 09 */ & Grp1A,
    /* 0A */ & Grp1A,
    /* 0B */ & Grp1A,
    /* 0C */ & UD,
    /* 0D */ & UD,
    /* 0E */ & UD,
    /* 0F */ & UD,

    /* 10 */ & Grp1A,
    /* 11 */ & Grp1A,
    /* 12 */ & Grp1A,
    /* 13 */ & Grp1A,
    /* 14 */ & UD,
    /* 15 */ & UD,
    /* 16 */ & UD,
    /* 17 */ & UD,
    /* 18 */ & UD,

    /* 19 */ & Grp1A,
    /* 1A */ & Grp1A,
    /* 1B */ & Grp1A,
    /* 1C */ & Grp1A,
    /* 1D */ & UD,
    /* 1E */ & UD,
    /* 1F */ & UD,

    /* 20 */ & Grp1A,
    /* 21 */ & Grp1A,
    /* 22 */ & Grp1A,
    /* 23 */ & Grp1A,
    /* 24 */ & UD,
    /* 25 */ & UD,
    /* 26 */ & UD,
    /* 27 */ & UD,

    /* 28 */ & Grp1A,
    /* 29 */ & Grp1A,
    /* 2A */ & Grp1A,
    /* 2B */ & Grp1A,
    /* 2C */ & UD,
    /* 2D */ & UD,
    /* 2E */ & UD,
    /* 2F */ & UD,

    /* 30 */ & Grp1A,
    /* 31 */ & Grp1A,
    /* 32 */ & Grp1A,
    /* 33 */ & Grp1A,
    /* 34 */ & UD,
    /* 35 */ & UD,
    /* 36 */ & UD,
    /* 37 */ & UD,

    /* 38 */ & Grp1A,
    /* 39 */ & Grp1A,
    /* 3A */ & Grp1A,
    /* 3B */ & Grp1A,
    /* 3C */ & UD,
    /* 3D */ & UD,
    /* 3E */ & UD,
    /* 3F */ & UD,

    /* 40 */ & UD,
    /* 41 */ & UD,
    /* 42 */ & UD,
    /* 43 */ & UD,
    /* 44 */ & UD,
    /* 45 */ & UD,
    /* 46 */ & UD,
    /* 47 */ & UD,
    /* 48 */ & UD,
    /* 49 */ & UD,
    /* 4A */ & UD,
    /* 4B */ & UD,
    /* 4C */ & UD,
    /* 4D */ & UD,
    /* 4E */ & UD,
    /* 4F */ & UD,

    /* 50 */ & UD,
    /* 51 */ & UD,
    /* 52 */ & UD,
    /* 53 */ & UD,
    /* 54 */ & UD,
    /* 55 */ & UD,
    /* 56 */ & UD,
    /* 57 */ & UD,
    /* 58 */ & UD,
    /* 59 */ & UD,
    /* 5A */ & UD,
    /* 5B */ & UD,
    /* 5C */ & UD,
    /* 5D */ & UD,
    /* 5E */ & UD,
    /* 5F */ & UD,

    /* 60 */ & UD,
    /* 61 */ & UD,
    /* 62 */ & UD,
    /* 63 */ & UD,
    /* 64 */ & UD,
    /* 65 */ & UD,
    /* 66 */ & UD,
    /* 67 */ & UD,

    /* 68 */ & UD,
    /* 69 */ & UD,
    /* 6A */ & UD,
    /* 6B */ & UD,
    /* 6C */ & UD,
    /* 6D */ & UD,
    /* 6E */ & UD,
    /* 6F */ & UD,

    /* 70 */ & UD,
    /* 71 */ & UD,
    /* 72 */ & UD,
    /* 73 */ & UD,
    /* 74 */ & UD,
    /* 75 */ & UD,
    /* 76 */ & UD,
    /* 77 */ & UD,

    /* 78 */ & UD,
    /* 79 */ & UD,
    /* 7A */ & UD,
    /* 7B */ & UD,
    /* 7C */ & UD,
    /* 7D */ & UD,
    /* 7E */ & UD,
    /* 7F */ & UD,

    /* 80 */ & UD,
    /* 81 */ & UD,
    /* 82 */ & UD,
    /* 83 */ & UD,
    /* 84 */ & UD,
    /* 85 */ & UD,
    /* 86 */ & UD,
    /* 87 */ & UD,

    /* 88 */ & UD,
    /* 89 */ & UD,
    /* 8A */ & UD,
    /* 8B */ & UD,
    /* 8C */ & UD,
    /* 8D */ & UD,
    /* 8E */ & UD,
    /* 8F */ & UD,

    /* 90 */ & UD,
    /* 91 */ & UD,
    /* 92 */ & UD,
    /* 93 */ & UD,
    /* 94 */ & UD,
    /* 95 */ & UD,
    /* 96 */ & UD,
    /* 97 */ & UD,

    /* 98 */ & UD,
    /* 99 */ & UD,
    /* 9A */ & UD,
    /* 9B */ & UD,
    /* 9C */ & UD,
    /* 9D */ & UD,
    /* 9E */ & UD,
    /* 9F */ & UD,

    /* A0 */ & UD,
    /* A1 */ & UD,
    /* A2 */ & UD,
    /* A3 */ & UD,
    /* A4 */ & UD,
    /* A5 */ & UD,
    /* A6 */ & UD,
    /* A7 */ & UD,

    /* A8 */ & UD,
    /* A9 */ & UD,
    /* AA */ & UD,
    /* AB */ & UD,
    /* AC */ & UD,
    /* AD */ & UD,
    /* AE */ & UD,
    /* AF */ & UD,

    /* B0 */ & UD,
    /* B1 */ & UD,
    /* B2 */ & UD,
    /* B3 */ & UD,
    /* B4 */ & UD,
    /* B5 */ & UD,
    /* B6 */ & UD,
    /* B7 */ & UD,

    /* B8 */ & UD,
    /* B9 */ & UD,
    /* BA */ & UD,
    /* BB */ & UD,
    /* BC */ & UD,
    /* BD */ & UD,
    /* BE */ & UD,
    /* BF */ & UD,

    /* C0 */ & UD,
    /* C1 */ & UD,
    /* C2 */ & UD,
    /* C3 */ & UD,
    /* C4 */ & UD,
    /* C5 */ & UD,
    /* C6 */ & UD,
    /* C7 */ & UD,

    /* C8 */ & UD,
    /* C9 */ & UD,
    /* CA */ & UD,
    /* CB */ & UD,
    /* CC */ & UD,
    /* CD */ & UD,
    /* CE */ & UD,
    /* CF */ & UD,

    /* D0 */ & UD,
    /* D1 */ & UD,
    /* D2 */ & UD,
    /* D3 */ & UD,
    /* D4 */ & UD,
    /* D5 */ & UD,
    /* D6 */ & UD,
    /* D7 */ & UD,

    /* D8 */ & UD,
    /* D9 */ & UD,
    /* DA */ & UD,
    /* DB */ & UD,
    /* DC */ & UD,
    /* DD */ & UD,
    /* DE */ & UD,
    /* DF */ & UD,

    /* E0 */ & UD,
    /* E1 */ & UD,
    /* E2 */ & UD,
    /* E3 */ & UD,
    /* E4 */ & UD,
    /* E5 */ & UD,
    /* E6 */ & UD,
    /* E7 */ & UD,

    /* E8 */ & UD,
    /* E9 */ & UD,
    /* EA */ & JUMPFAR,
    /* EB */ & UD,
    /* EC */ & UD,
    /* ED */ & UD,
    /* EE */ & UD,
    /* EF */ & UD,

    /* F0 */ & UD,
    /* F1 */ & UD,
    /* F2 */ & UD,
    /* F3 */ & UD,
    /* F4 */ & UD,
    /* F5 */ & CMC,
    /* F6 */ & UD,
    /* F7 */ & UD,

    /* F8 */ & CLC,
    /* F9 */ & STC,
    /* FA */ & CLI,
    /* FB */ & STI,
    /* FC */ & CLD,
    /* FD */ & STD,
    /* FE */ & UD,
    /* FF */ & UD,
};
